### ISSUE TITLE
Adicionar link para submissão de palestras e tutoriais

### ISSUE THREAD

**Issue by jjpaulo2** [pythonNordeste/pyne2024#18]
https://www.even3.com.br/python-nordeste-2024/

**Comment by jjpaulo2** [comment]
@HigorMonteiro vc quer tocar essa issue?

**Comment by jjpaulo2** [comment]
![image](https://github.com/pythonNordeste/pyne2024/assets/22819523/a208edd4-e928-414d-abcc-add00010ec48)

talvez já adicionar um link em destaque bem nesse início seja legal (onde eu marquei de vermelho)

podemos adicionar também no menu superior, pra ficar acessível caso a pessoa role a página

**Comment by HigorMonteiro** [comment]
Vou dar inicio nessa issue, desculpa a demora ;)

**Comment by HigorMonteiro** [comment]
@jjpaulo2 @itepifanio desculpa a demora galera, ficou dessa forma, o que acham? Posso mudar a cor e o texto se for o caso.
![Captura de Tela 2024-02-01 às 08 05 41](https://github.com/pythonNordeste/pyne2024/assets/7028769/a839d142-11cd-4e16-b599-6b42f59de255)

**Comment by itepifanio** [comment]
> @jjpaulo2 @itepifanio desculpa a demora galera, ficou dessa forma, o que acham? Posso mudar a cor e o texto se for o caso. 

Opa, @HigorMonteiro, gostei demais das cores e do botão e do local. Vou fazer algumas sugestões de melhoria de texto do botão, mas fique a vontade pra alterar pra descrição que fizer mais sentido pra você.

Somente "submissões" não descreve muito bem a ação, eu sugeriria "Chamada de atividades", não sei se um ícone de microfone faria sentido junto ao botão (🎙️). Também colocaria um tooltip pra quando a pessoa passasse o mouse aparecesse algo como "Submeta palestras ou tutoriais e contribua para a programação da Python Nordeste".

**Comment by jjpaulo2** [comment]
Boa. Gostei das ideias do @itepifanio

**Comment by HigorMonteiro** [comment]
@itepifanio @jjpaulo2 quando puderem deem uma olhadinha, qualquer sugestão de melhoria é sempre bem vinda ;) 
@itepifanio vlwzão pelas dicas, ficou bem melhor agora.

**Comment by itepifanio** [comment]
@HigorMonteiro achei só a mensagem do tooltip um pouco repetitiva, poderia só alterar para `Submeta palestras ou tutoriais e contribua para a programação da Python Nordeste` ou algum outro texto explicando do que se trata a submissão de atividades?

Depois dessa alteração acho que já podemos aprovar e tudo certo :)
