### ISSUE TITLE
Adicionar seção de patrocinadores conforme especificado no Figma

### ISSUE THREAD

**Issue by HigorMonteiro** [pythonNordeste/pyne2024#19]
### Descrição:
Estamos planejando implementar uma nova seção em nosso site dedicada aos nossos patrocinadores. Conforme detalhado no Figma, a seção de patrocinadores será uma adição valiosa para destacar e reconhecer aqueles que apoiam nossa iniciativa.

### Detalhes da Tarefa:

Criar a seção de patrocinadores conforme as especificações fornecidas no Figma.
Testar a aparência e a funcionalidade da seção em diferentes tamanhos de tela, incluindo smartphone, tablet, desktop e ultrawide.
Garantir que a seção seja responsiva e se adapte corretamente a cada tamanho de tela.
Adicionar imagens de printscreens ao abrir o pull request referente a esta feature, demonstrando como a seção aparece em diferentes dispositivos.

**Recursos:**

- **Link para o Figma:** 🎨  [ https://www.figma.com/PyNE24 ](https://www.figma.com/proto/f4OyB0qfkm8YTIWqNpZ7jl/PYTHON-NORDESTE-24?page-id=3%3A120&type=design&node-id=64-2187&viewport=1951%2C1755%2C0.65&t=Ki4IINLLNx313ZbM-1&scaling=min-zoom)
- **Imagem de referência:** 🖨️ 
![Captura de Tela 2024-02-01 às 08 23 42](https://github.com/pythonNordeste/pyne2024/assets/7028769/bd8954e5-6c18-48e9-88b0-30b7be0c73e2)

### Observações:
Certifique-se de seguir as diretrizes de design e estilo do nosso site durante a implementação da seção de patrocinadores. Se houver alguma dúvida sobre as especificações ou requisitos, por favor, não hesite em entrar em contato para esclarecimentos adicionais.

**Comment by jjpaulo2** [comment]
@itepifanio já tem algum patrocinador confirmado pra já fazer essa inclusão no site?

**Comment by itepifanio** [comment]
> @itepifanio já tem algum patrocinador confirmado pra já fazer essa inclusão no site?

Já sim @jjpaulo2. Eu verifica as issues #20 e #21 eu tinha adicionado elas no repositório geral da organização, mas transferi para cá

**Comment by jjpaulo2** [comment]
Shooow! Consigo fazer essa adição ainda hoje!
