### ISSUE TITLE
Adicionar logo da Vinta na seção de patrocinadores 

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/pyne2024#20]
A prototipação da seção dos patrocinadores foi feita na issue pythonNordeste/organizacao-pyne-2024#6

Para finalizar essa issue deve-se:

- [ ] Criar seção de patrocinadores
- [ ] Adicionar logo da Vinta na cota bronze seguindo o tamanho 100x100

**Comment by jjpaulo2** [comment]
@itepifanio solicitei acesso ao drive

**Comment by itepifanio** [comment]
@jjpaulo2 dei acesso, poderia confirmar se tá tudo certo?

**Comment by jjpaulo2** [comment]
Valeeu @itepifanio acesso recebido aqui.
Será se teria como liberar acesso à pasta com todas as logos?
Pra evitar toda vez ter que liberar

**Comment by HigorMonteiro** [comment]
Ficou muito massa, parabéns !!!
