### ISSUE TITLE
Adicionar logo do Sebrae e Sebraelab na seção de patrocinadores

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/pyne2024#21]
A seção de patrocinadores já deve ter sido adicionada na issue pythonNordeste/pyne2024#20, essa seção deve adicionar as logos do Sebrae e Sebraelab como apoio do evento. Pode-se utilizar os mesmos tamanhos da cota cobre.

**Comment by jjpaulo2** [comment]
Farei essa adição

**Comment by jjpaulo2** [comment]
@itepifanio será uma **nova seção** de apoiadores, certo?

Coloco abaixo dos patrocinadores?
Onde eu posso pegar as logos?

**Comment by itepifanio** [comment]
> @itepifanio será uma nova seção de apoiadores, certo? Coloco abaixo dos patrocinadores?

@jjpaulo2 isso, pode colocar abaixo dos patrocinadores.

> Onde eu posso pegar as logos?

Coloquei as duas logos [no drive](https://drive.google.com/drive/folders/1365RSgC6Np5uR0uIb-_FujDReKyUOm2V?usp=drive_link).

**Comment by jjpaulo2** [comment]
@itepifanio feito! Pode conferir se a forma como eu fiz, condiz com o esperado?
