### ISSUE TITLE
Ajuste de margens, espaçamentos e seções

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/pyne2024#24]
Ajustar os espaçamentos e seções com base na [prototipação figma](https://www.figma.com/proto/f4OyB0qfkm8YTIWqNpZ7jl/PYTHON-NORDESTE-24?page-id=3%3A120&type=design&node-id=64-2187&viewport=1951%2C1755%2C0.65&t=Ki4IINLLNx313ZbM-1&scaling=min-zoom&mode=design) feito pelo @lucasleninsa

**Comment by itepifanio** [comment]
@HigorMonteiro tu acha que poderia pegar essa issue aqui?

**Comment by HigorMonteiro** [comment]
@itepifanio consigo sim :) irei trabalhar nela

**Comment by itepifanio** [comment]
@HigorMonteiro peguei um fim de semana com o designer do site pra atualizar ele. Ainda falta uns ajustes mais finos, irei adicionar novas issues logo mais.
