### ISSUE TITLE
Criação da página de Financiamento coletivo

### ISSUE THREAD

**Issue by allythy** [pythonNordeste/pyne2024#29]
A página vai conter algumas sessão como: 

- Financiamento coletivo: informações gerais sobre.
- Meta: O valor a ser arrecadado de 5 mil reais.
-  Valor arrecadado: Mostra o valor arrecado no dia. O valor será atualizado uma vez por dia. 
- Como doar: Chave pix e informacoes da conta
- Lista dos(as) doadores(as): pessoas que apoiaram o financiamento

Pode ter como passe o financiamento da MiniDebConf: https://bh.mini.debconf.org/doacoes/

**Comment by HigorMonteiro** [comment]
@allythy desculpa a demora, esse é o[#30 PR]( https://github.com/pythonNordeste/pyne2024/pull/30#issue-2300523547)
