### ISSUE TITLE
Adicionar grade do evento no site

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/pyne2024#32]
Adicionar uma nova página que contenha a grade do evento. O template deve seguir o padrão da edição 2022, como segue:

<img width="740" alt="image" src="https://github.com/pythonNordeste/pyne2024/assets/6730205/6b6f3c34-bffb-4e7d-8986-eb774a7a1d26">

Tal padrão é a foto do palestrante, seguido do seu título. Um bônus seria permitir ao usuário clicar e verificar o resumo da atividade.

Para adicionar o novo menu "Palestras", remove um dos dois `PATROCÍNIO/PATROCINADORAS` apontando ele apenas para os atuais patrocinadores.

O nome dos palestrantes, minibio, atividades e resumo consta aqui: https://docs.google.com/spreadsheets/d/1m47WJBCeAYbPVXKs9x4zii14ZHw3kh2dtQNdnyCTO2g/edit?usp=drive_link

As fotos dos palestrantes seguem aqui: https://drive.google.com/drive/folders/1JaH_b6kQXSng-eEX71NJ2qQLerwbu9AL?usp=drive_link

Os slots das palestras seguem aqui: https://docs.google.com/spreadsheets/d/1iYeFJALRzAP8y9Cb_DSkYg5MObQu9H-jLrQj6R6G5bo/edit?usp=sharing

**Comment by HigorMonteiro** [comment]
@itepifanio poderia colocar a data limite para entrega? Algum lembrete ou algo do tipo? Isso vai nos ajudar a não atrasar essa entrega :|
Já estou vendo o melhor momento para eu me concentrar nessa entrega ;)

**Comment by itepifanio** [comment]
@HigorMonteiro adicionei a data limite, mas caso precise de mais tempo ou ajuda basta pingar a gente. Quanto ao lembrete eu acho que o github não tem essa funcionalidade :/

<img width="235" alt="image" src="https://github.com/pythonNordeste/pyne2024/assets/6730205/e6c01853-24b6-4c0b-ab2a-a94112b7f873">

**Comment by itepifanio** [comment]
Valeu pela ajuda @HigorMonteiro !
