### ISSUE TITLE
Salvar estado do card na agenda

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/pyne2024#35]
Atualmente a grade do evento não salva qual o último card que o usuário acessou. Sem esse estado o usuário tem que mudar o dia do evento sempre.

Para resolver isso, o estado do card atual deve ser armazenado e recuperado ao carregar o site, seja através de cookie, local storage, etc

**Comment by jjpaulo2** [comment]
@itepifanio ainda faz sentido essa correção?

**Comment by itepifanio** [comment]
@jjpaulo2 bem observado, não precisa, vou fechar
