### ISSUE TITLE
Abrir modal com locais do evento apenas uma vez

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/pyne2024#43]
Salvar no cache/local storage se o usuário já viu o modal com as informações sobre CDC e local do evento

**Comment by itepifanio** [comment]
Isso, agradeço @jjpaulo2

**Comment by jjpaulo2** [comment]
@itepifanio resolvido!

**Comment by itepifanio** [comment]
Grato @jjpaulo2!
