### ISSUE TITLE
Atualizar link de redirecionamento para a Save In Cloud

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/pyne2024#45]
https://saveincloud.com/pt/blog/solucoes-web/vantagens-python-em-cloud/

**Comment by jjpaulo2** [comment]
@itepifanio ainda precisa atualizar isso?
Vi que tem um commit sobre essa atualização

**Comment by itepifanio** [comment]
Não, commitei e esqueci de fechar, valeu @jjpaulo2!
